/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.39
 * Generated at: 2023-09-09 11:39:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\" data-bs-theme=\"auto\">\r\n");
      out.write("  <head><script src=\"/docs/5.3/assets/js/color-modes.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"author\" content=\"Mark Otto, Jacob Thornton, 그리고 Bootstrap 기여자들\">\r\n");
      out.write("    <meta name=\"generator\" content=\"Hugo 0.115.4\">\r\n");
      out.write("    <title>Sidebars · Bootstrap v5.3</title>\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"canonical\" href=\"https://getbootstrap.kr/docs/5.3/examples/sidebars/\">\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/@docsearch/css@3\">\r\n");
      out.write("\r\n");
      out.write("<link href=\"/docs/5.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9\" crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Favicons -->\r\n");
      out.write("<link rel=\"apple-touch-icon\" href=\"/docs/5.3/assets/img/favicons/apple-touch-icon.png\" sizes=\"180x180\">\r\n");
      out.write("<link rel=\"icon\" href=\"/docs/5.3/assets/img/favicons/favicon-32x32.png\" sizes=\"32x32\" type=\"image/png\">\r\n");
      out.write("<link rel=\"icon\" href=\"/docs/5.3/assets/img/favicons/favicon-16x16.png\" sizes=\"16x16\" type=\"image/png\">\r\n");
      out.write("<link rel=\"manifest\" href=\"/docs/5.3/assets/img/favicons/manifest.json\">\r\n");
      out.write("<link rel=\"mask-icon\" href=\"/docs/5.3/assets/img/favicons/safari-pinned-tab.svg\" color=\"#712cf9\">\r\n");
      out.write("<link rel=\"icon\" href=\"/docs/5.3/assets/img/favicons/favicon.ico\">\r\n");
      out.write("<meta name=\"theme-color\" content=\"#712cf9\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("      .bd-placeholder-img {\r\n");
      out.write("        font-size: 1.125rem;\r\n");
      out.write("        text-anchor: middle;\r\n");
      out.write("        -webkit-user-select: none;\r\n");
      out.write("        -moz-user-select: none;\r\n");
      out.write("        user-select: none;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      @media (min-width: 768px) {\r\n");
      out.write("        .bd-placeholder-img-lg {\r\n");
      out.write("          font-size: 3.5rem;\r\n");
      out.write("        }\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .b-example-divider {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        height: 3rem;\r\n");
      out.write("        background-color: rgba(0, 0, 0, .1);\r\n");
      out.write("        border: solid rgba(0, 0, 0, .15);\r\n");
      out.write("        border-width: 1px 0;\r\n");
      out.write("        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .b-example-vr {\r\n");
      out.write("        flex-shrink: 0;\r\n");
      out.write("        width: 1.5rem;\r\n");
      out.write("        height: 100vh;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .bi {\r\n");
      out.write("        vertical-align: -.125em;\r\n");
      out.write("        fill: currentColor;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .nav-scroller {\r\n");
      out.write("        position: relative;\r\n");
      out.write("        z-index: 2;\r\n");
      out.write("        height: 2.75rem;\r\n");
      out.write("        overflow-y: hidden;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .nav-scroller .nav {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        flex-wrap: nowrap;\r\n");
      out.write("        padding-bottom: 1rem;\r\n");
      out.write("        margin-top: -1px;\r\n");
      out.write("        overflow-x: auto;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        white-space: nowrap;\r\n");
      out.write("        -webkit-overflow-scrolling: touch;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .btn-bd-primary {\r\n");
      out.write("        --bd-violet-bg: #712cf9;\r\n");
      out.write("        --bd-violet-rgb: 112.520718, 44.062154, 249.437846;\r\n");
      out.write("\r\n");
      out.write("        --bs-btn-font-weight: 600;\r\n");
      out.write("        --bs-btn-color: var(--bs-white);\r\n");
      out.write("        --bs-btn-bg: var(--bd-violet-bg);\r\n");
      out.write("        --bs-btn-border-color: var(--bd-violet-bg);\r\n");
      out.write("        --bs-btn-hover-color: var(--bs-white);\r\n");
      out.write("        --bs-btn-hover-bg: #6528e0;\r\n");
      out.write("        --bs-btn-hover-border-color: #6528e0;\r\n");
      out.write("        --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);\r\n");
      out.write("        --bs-btn-active-color: var(--bs-btn-hover-color);\r\n");
      out.write("        --bs-btn-active-bg: #5a23c8;\r\n");
      out.write("        --bs-btn-active-border-color: #5a23c8;\r\n");
      out.write("      }\r\n");
      out.write("      .bd-mode-toggle {\r\n");
      out.write("        z-index: 1500;\r\n");
      out.write("      }\r\n");
      out.write("    </style>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <!-- Custom styles for this template -->\r\n");
      out.write("    <link href=\"sidebars.css\" rel=\"stylesheet\">\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("    <svg xmlns=\"http://www.w3.org/2000/svg\" class=\"d-none\">\r\n");
      out.write("      <symbol id=\"check2\" viewBox=\"0 0 16 16\">\r\n");
      out.write("        <path d=\"M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z\"/>\r\n");
      out.write("      </symbol>\r\n");
      out.write("      <symbol id=\"circle-half\" viewBox=\"0 0 16 16\">\r\n");
      out.write("        <path d=\"M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z\"/>\r\n");
      out.write("      </symbol>\r\n");
      out.write("      <symbol id=\"moon-stars-fill\" viewBox=\"0 0 16 16\">\r\n");
      out.write("        <path d=\"M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z\"/>\r\n");
      out.write("        <path d=\"M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z\"/>\r\n");
      out.write("      </symbol>\r\n");
      out.write("      <symbol id=\"sun-fill\" viewBox=\"0 0 16 16\">\r\n");
      out.write("        <path d=\"M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z\"/>\r\n");
      out.write("      </symbol>\r\n");
      out.write("    </svg>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle\">\r\n");
      out.write("      <button class=\"btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center\"\r\n");
      out.write("              id=\"bd-theme\"\r\n");
      out.write("              type=\"button\"\r\n");
      out.write("              aria-expanded=\"false\"\r\n");
      out.write("              data-bs-toggle=\"dropdown\"\r\n");
      out.write("              aria-label=\"Toggle theme (auto)\">\r\n");
      out.write("        <svg class=\"bi my-1 theme-icon-active\" width=\"1em\" height=\"1em\"><use href=\"#circle-half\"></use></svg>\r\n");
      out.write("        <span class=\"visually-hidden\" id=\"bd-theme-text\">Toggle theme</span>\r\n");
      out.write("      </button>\r\n");
      out.write("      <ul class=\"dropdown-menu dropdown-menu-end shadow\" aria-labelledby=\"bd-theme-text\">\r\n");
      out.write("        <li>\r\n");
      out.write("          <button type=\"button\" class=\"dropdown-item d-flex align-items-center\" data-bs-theme-value=\"light\" aria-pressed=\"false\">\r\n");
      out.write("            <svg class=\"bi me-2 opacity-50 theme-icon\" width=\"1em\" height=\"1em\"><use href=\"#sun-fill\"></use></svg>\r\n");
      out.write("            Light\r\n");
      out.write("            <svg class=\"bi ms-auto d-none\" width=\"1em\" height=\"1em\"><use href=\"#check2\"></use></svg>\r\n");
      out.write("          </button>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li>\r\n");
      out.write("          <button type=\"button\" class=\"dropdown-item d-flex align-items-center\" data-bs-theme-value=\"dark\" aria-pressed=\"false\">\r\n");
      out.write("            <svg class=\"bi me-2 opacity-50 theme-icon\" width=\"1em\" height=\"1em\"><use href=\"#moon-stars-fill\"></use></svg>\r\n");
      out.write("            Dark\r\n");
      out.write("            <svg class=\"bi ms-auto d-none\" width=\"1em\" height=\"1em\"><use href=\"#check2\"></use></svg>\r\n");
      out.write("          </button>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li>\r\n");
      out.write("          <button type=\"button\" class=\"dropdown-item d-flex align-items-center active\" data-bs-theme-value=\"auto\" aria-pressed=\"true\">\r\n");
      out.write("            <svg class=\"bi me-2 opacity-50 theme-icon\" width=\"1em\" height=\"1em\"><use href=\"#circle-half\"></use></svg>\r\n");
      out.write("            Auto\r\n");
      out.write("            <svg class=\"bi ms-auto d-none\" width=\"1em\" height=\"1em\"><use href=\"#check2\"></use></svg>\r\n");
      out.write("          </button>\r\n");
      out.write("        </li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<svg xmlns=\"http://www.w3.org/2000/svg\" class=\"d-none\">\r\n");
      out.write("  <symbol id=\"bootstrap\" viewBox=\"0 0 118 94\">\r\n");
      out.write("    <title>Bootstrap</title>\r\n");
      out.write("    <path fill-rule=\"evenodd\" clip-rule=\"evenodd\" d=\"M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z\"></path>\r\n");
      out.write("  </symbol>\r\n");
      out.write("  <symbol id=\"home\" viewBox=\"0 0 16 16\">\r\n");
      out.write("    <path d=\"M8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4.5a.5.5 0 0 0 .5-.5v-4h2v4a.5.5 0 0 0 .5.5H14a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146zM2.5 14V7.707l5.5-5.5 5.5 5.5V14H10v-4a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5v4H2.5z\"/>\r\n");
      out.write("  </symbol>\r\n");
      out.write("  <symbol id=\"speedometer2\" viewBox=\"0 0 16 16\">\r\n");
      out.write("    <path d=\"M8 4a.5.5 0 0 1 .5.5V6a.5.5 0 0 1-1 0V4.5A.5.5 0 0 1 8 4zM3.732 5.732a.5.5 0 0 1 .707 0l.915.914a.5.5 0 1 1-.708.708l-.914-.915a.5.5 0 0 1 0-.707zM2 10a.5.5 0 0 1 .5-.5h1.586a.5.5 0 0 1 0 1H2.5A.5.5 0 0 1 2 10zm9.5 0a.5.5 0 0 1 .5-.5h1.5a.5.5 0 0 1 0 1H12a.5.5 0 0 1-.5-.5zm.754-4.246a.389.389 0 0 0-.527-.02L7.547 9.31a.91.91 0 1 0 1.302 1.258l3.434-4.297a.389.389 0 0 0-.029-.518z\"/>\r\n");
      out.write("    <path fill-rule=\"evenodd\" d=\"M0 10a8 8 0 1 1 15.547 2.661c-.442 1.253-1.845 1.602-2.932 1.25C11.309 13.488 9.475 13 8 13c-1.474 0-3.31.488-4.615.911-1.087.352-2.49.003-2.932-1.25A7.988 7.988 0 0 1 0 10zm8-7a7 7 0 0 0-6.603 9.329c.203.575.923.876 1.68.63C4.397 12.533 6.358 12 8 12s3.604.532 4.923.96c.757.245 1.477-.056 1.68-.631A7 7 0 0 0 8 3z\"/>\r\n");
      out.write("  </symbol>\r\n");
      out.write("  <symbol id=\"table\" viewBox=\"0 0 16 16\">\r\n");
      out.write("    <path d=\"M0 2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2zm15 2h-4v3h4V4zm0 4h-4v3h4V8zm0 4h-4v3h3a1 1 0 0 0 1-1v-2zm-5 3v-3H6v3h4zm-5 0v-3H1v2a1 1 0 0 0 1 1h3zm-4-4h4V8H1v3zm0-4h4V4H1v3zm5-3v3h4V4H6zm4 4H6v3h4V8z\"/>\r\n");
      out.write("  </symbol>\r\n");
      out.write("  <symbol id=\"people-circle\" viewBox=\"0 0 16 16\">\r\n");
      out.write("    <path d=\"M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z\"/>\r\n");
      out.write("    <path fill-rule=\"evenodd\" d=\"M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z\"/>\r\n");
      out.write("  </symbol>\r\n");
      out.write("  <symbol id=\"grid\" viewBox=\"0 0 16 16\">\r\n");
      out.write("    <path d=\"M1 2.5A1.5 1.5 0 0 1 2.5 1h3A1.5 1.5 0 0 1 7 2.5v3A1.5 1.5 0 0 1 5.5 7h-3A1.5 1.5 0 0 1 1 5.5v-3zM2.5 2a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zm6.5.5A1.5 1.5 0 0 1 10.5 1h3A1.5 1.5 0 0 1 15 2.5v3A1.5 1.5 0 0 1 13.5 7h-3A1.5 1.5 0 0 1 9 5.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zM1 10.5A1.5 1.5 0 0 1 2.5 9h3A1.5 1.5 0 0 1 7 10.5v3A1.5 1.5 0 0 1 5.5 15h-3A1.5 1.5 0 0 1 1 13.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zm6.5.5A1.5 1.5 0 0 1 10.5 9h3a1.5 1.5 0 0 1 1.5 1.5v3a1.5 1.5 0 0 1-1.5 1.5h-3A1.5 1.5 0 0 1 9 13.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3z\"/>\r\n");
      out.write("  </symbol>\r\n");
      out.write("</svg>\r\n");
      out.write("\r\n");
      out.write("<main class=\"d-flex flex-nowrap\">\r\n");
      out.write("  <h1 class=\"visually-hidden\">Sidebars examples</h1>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"d-flex flex-column flex-shrink-0 p-3 text-bg-dark\" style=\"width: 280px;\">\r\n");
      out.write("    <a href=\"/\" class=\"d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none\">\r\n");
      out.write("      <svg class=\"bi pe-none me-2\" width=\"40\" height=\"32\"><use xlink:href=\"#bootstrap\"/></svg>\r\n");
      out.write("      <span class=\"fs-4\">Sidebar</span>\r\n");
      out.write("    </a>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"b-example-divider b-example-vr\"></div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"d-flex flex-column flex-shrink-0 bg-body-tertiary\" style=\"width: 4.5rem;\">\r\n");
      out.write("    <a href=\"/\" class=\"d-block p-3 link-body-emphasis text-decoration-none\" title=\"Icon-only\" data-bs-toggle=\"tooltip\" data-bs-placement=\"right\">\r\n");
      out.write("      <svg class=\"bi pe-none\" width=\"40\" height=\"32\"><use xlink:href=\"#bootstrap\"/></svg>\r\n");
      out.write("      <span class=\"visually-hidden\">Icon-only</span>\r\n");
      out.write("    </a>\r\n");
      out.write("    <ul class=\"nav nav-pills nav-flush flex-column mb-auto text-center\">\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a href=\"#\" class=\"nav-link active py-3 border-bottom rounded-0\" aria-current=\"page\" title=\"Home\" data-bs-toggle=\"tooltip\" data-bs-placement=\"right\">\r\n");
      out.write("          <svg class=\"bi pe-none\" width=\"24\" height=\"24\" role=\"img\" aria-label=\"Home\"><use xlink:href=\"#home\"/></svg>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li>\r\n");
      out.write("        <a href=\"#\" class=\"nav-link py-3 border-bottom rounded-0\" title=\"Dashboard\" data-bs-toggle=\"tooltip\" data-bs-placement=\"right\">\r\n");
      out.write("          <svg class=\"bi pe-none\" width=\"24\" height=\"24\" role=\"img\" aria-label=\"Dashboard\"><use xlink:href=\"#speedometer2\"/></svg>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li>\r\n");
      out.write("        <a href=\"#\" class=\"nav-link py-3 border-bottom rounded-0\" title=\"Orders\" data-bs-toggle=\"tooltip\" data-bs-placement=\"right\">\r\n");
      out.write("          <svg class=\"bi pe-none\" width=\"24\" height=\"24\" role=\"img\" aria-label=\"Orders\"><use xlink:href=\"#table\"/></svg>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li>\r\n");
      out.write("        <a href=\"#\" class=\"nav-link py-3 border-bottom rounded-0\" title=\"Products\" data-bs-toggle=\"tooltip\" data-bs-placement=\"right\">\r\n");
      out.write("          <svg class=\"bi pe-none\" width=\"24\" height=\"24\" role=\"img\" aria-label=\"Products\"><use xlink:href=\"#grid\"/></svg>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li>\r\n");
      out.write("        <a href=\"#\" class=\"nav-link py-3 border-bottom rounded-0\" title=\"Customers\" data-bs-toggle=\"tooltip\" data-bs-placement=\"right\">\r\n");
      out.write("          <svg class=\"bi pe-none\" width=\"24\" height=\"24\" role=\"img\" aria-label=\"Customers\"><use xlink:href=\"#people-circle\"/></svg>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>\r\n");
      out.write("    </ul>\r\n");
      out.write("    <div class=\"dropdown border-top\">\r\n");
      out.write("      <a href=\"#\" class=\"d-flex align-items-center justify-content-center p-3 link-body-emphasis text-decoration-none dropdown-toggle\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("        <img src=\"https://github.com/mdo.png\" alt=\"mdo\" width=\"24\" height=\"24\" class=\"rounded-circle\">\r\n");
      out.write("      </a>\r\n");
      out.write("      <ul class=\"dropdown-menu text-small shadow\">\r\n");
      out.write("        <li><a class=\"dropdown-item\" href=\"#\">New project...</a></li>\r\n");
      out.write("        <li><a class=\"dropdown-item\" href=\"#\">Settings</a></li>\r\n");
      out.write("        <li><a class=\"dropdown-item\" href=\"#\">Profile</a></li>\r\n");
      out.write("        <li><hr class=\"dropdown-divider\"></li>\r\n");
      out.write("        <li><a class=\"dropdown-item\" href=\"#\">Sign out</a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"b-example-divider b-example-vr\"></div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"flex-shrink-0 p-3\" style=\"width: 280px;\">\r\n");
      out.write("    <a href=\"/\" class=\"d-flex align-items-center pb-3 mb-3 link-body-emphasis text-decoration-none border-bottom\">\r\n");
      out.write("      <svg class=\"bi pe-none me-2\" width=\"30\" height=\"24\"><use xlink:href=\"#bootstrap\"/></svg>\r\n");
      out.write("      <span class=\"fs-5 fw-semibold\">Collapsible</span>\r\n");
      out.write("    </a>\r\n");
      out.write("    <ul class=\"list-unstyled ps-0\">\r\n");
      out.write("      <li class=\"mb-1\">\r\n");
      out.write("        <button class=\"btn btn-toggle d-inline-flex align-items-center rounded border-0 collapsed\" data-bs-toggle=\"collapse\" data-bs-target=\"#home-collapse\" aria-expanded=\"true\">\r\n");
      out.write("          Home\r\n");
      out.write("        </button>\r\n");
      out.write("        <div class=\"collapse show\" id=\"home-collapse\">\r\n");
      out.write("          <ul class=\"btn-toggle-nav list-unstyled fw-normal pb-1 small\">\r\n");
      out.write("            <li><a href=\"#\" class=\"link-body-emphasis d-inline-flex text-decoration-none rounded\">Overview</a></li>\r\n");
      out.write("            <li><a href=\"#\" class=\"link-body-emphasis d-inline-flex text-decoration-none rounded\">Updates</a></li>\r\n");
      out.write("            <li><a href=\"#\" class=\"link-body-emphasis d-inline-flex text-decoration-none rounded\">Reports</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"mb-1\">\r\n");
      out.write("        <button class=\"btn btn-toggle d-inline-flex align-items-center rounded border-0 collapsed\" data-bs-toggle=\"collapse\" data-bs-target=\"#dashboard-collapse\" aria-expanded=\"false\">\r\n");
      out.write("          Dashboard\r\n");
      out.write("        </button>\r\n");
      out.write("        <div class=\"collapse\" id=\"dashboard-collapse\">\r\n");
      out.write("          <ul class=\"btn-toggle-nav list-unstyled fw-normal pb-1 small\">\r\n");
      out.write("            <li><a href=\"#\" class=\"link-body-emphasis d-inline-flex text-decoration-none rounded\">Overview</a></li>\r\n");
      out.write("            <li><a href=\"#\" class=\"link-body-emphasis d-inline-flex text-decoration-none rounded\">Weekly</a></li>\r\n");
      out.write("            <li><a href=\"#\" class=\"link-body-emphasis d-inline-flex text-decoration-none rounded\">Monthly</a></li>\r\n");
      out.write("            <li><a href=\"#\" class=\"link-body-emphasis d-inline-flex text-decoration-none rounded\">Annually</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"mb-1\">\r\n");
      out.write("        <button class=\"btn btn-toggle d-inline-flex align-items-center rounded border-0 collapsed\" data-bs-toggle=\"collapse\" data-bs-target=\"#orders-collapse\" aria-expanded=\"false\">\r\n");
      out.write("          Orders\r\n");
      out.write("        </button>\r\n");
      out.write("        <div class=\"collapse\" id=\"orders-collapse\">\r\n");
      out.write("          <ul class=\"btn-toggle-nav list-unstyled fw-normal pb-1 small\">\r\n");
      out.write("            <li><a href=\"#\" class=\"link-body-emphasis d-inline-flex text-decoration-none rounded\">New</a></li>\r\n");
      out.write("            <li><a href=\"#\" class=\"link-body-emphasis d-inline-flex text-decoration-none rounded\">Processed</a></li>\r\n");
      out.write("            <li><a href=\"#\" class=\"link-body-emphasis d-inline-flex text-decoration-none rounded\">Shipped</a></li>\r\n");
      out.write("            <li><a href=\"#\" class=\"link-body-emphasis d-inline-flex text-decoration-none rounded\">Returned</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"border-top my-3\"></li>\r\n");
      out.write("      <li class=\"mb-1\">\r\n");
      out.write("        <button class=\"btn btn-toggle d-inline-flex align-items-center rounded border-0 collapsed\" data-bs-toggle=\"collapse\" data-bs-target=\"#account-collapse\" aria-expanded=\"false\">\r\n");
      out.write("          Account\r\n");
      out.write("        </button>\r\n");
      out.write("        <div class=\"collapse\" id=\"account-collapse\">\r\n");
      out.write("          <ul class=\"btn-toggle-nav list-unstyled fw-normal pb-1 small\">\r\n");
      out.write("            <li><a href=\"#\" class=\"link-body-emphasis d-inline-flex text-decoration-none rounded\">New...</a></li>\r\n");
      out.write("            <li><a href=\"#\" class=\"link-body-emphasis d-inline-flex text-decoration-none rounded\">Profile</a></li>\r\n");
      out.write("            <li><a href=\"#\" class=\"link-body-emphasis d-inline-flex text-decoration-none rounded\">Settings</a></li>\r\n");
      out.write("            <li><a href=\"#\" class=\"link-body-emphasis d-inline-flex text-decoration-none rounded\">Sign out</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("      </li>\r\n");
      out.write("    </ul>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"b-example-divider b-example-vr\"></div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"d-flex flex-column align-items-stretch flex-shrink-0 bg-body-tertiary\" style=\"width: 380px;\">\r\n");
      out.write("    <a href=\"/\" class=\"d-flex align-items-center flex-shrink-0 p-3 link-body-emphasis text-decoration-none border-bottom\">\r\n");
      out.write("      <svg class=\"bi pe-none me-2\" width=\"30\" height=\"24\"><use xlink:href=\"#bootstrap\"/></svg>\r\n");
      out.write("      <span class=\"fs-5 fw-semibold\">List group</span>\r\n");
      out.write("    </a>\r\n");
      out.write("    <div class=\"list-group list-group-flush border-bottom scrollarea\">\r\n");
      out.write("      <a href=\"#\" class=\"list-group-item list-group-item-action active py-3 lh-sm\" aria-current=\"true\">\r\n");
      out.write("        <div class=\"d-flex w-100 align-items-center justify-content-between\">\r\n");
      out.write("          <strong class=\"mb-1\">List group item heading</strong>\r\n");
      out.write("          <small>Wed</small>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-10 mb-1 small\">Some placeholder content in a paragraph below the heading and date.</div>\r\n");
      out.write("      </a>\r\n");
      out.write("      <a href=\"#\" class=\"list-group-item list-group-item-action py-3 lh-sm\">\r\n");
      out.write("        <div class=\"d-flex w-100 align-items-center justify-content-between\">\r\n");
      out.write("          <strong class=\"mb-1\">List group item heading</strong>\r\n");
      out.write("          <small class=\"text-body-secondary\">Tues</small>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-10 mb-1 small\">Some placeholder content in a paragraph below the heading and date.</div>\r\n");
      out.write("      </a>\r\n");
      out.write("      <a href=\"#\" class=\"list-group-item list-group-item-action py-3 lh-sm\">\r\n");
      out.write("        <div class=\"d-flex w-100 align-items-center justify-content-between\">\r\n");
      out.write("          <strong class=\"mb-1\">List group item heading</strong>\r\n");
      out.write("          <small class=\"text-body-secondary\">Mon</small>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-10 mb-1 small\">Some placeholder content in a paragraph below the heading and date.</div>\r\n");
      out.write("      </a>\r\n");
      out.write("\r\n");
      out.write("      <a href=\"#\" class=\"list-group-item list-group-item-action py-3 lh-sm\" aria-current=\"true\">\r\n");
      out.write("        <div class=\"d-flex w-100 align-items-center justify-content-between\">\r\n");
      out.write("          <strong class=\"mb-1\">List group item heading</strong>\r\n");
      out.write("          <small class=\"text-body-secondary\">Wed</small>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-10 mb-1 small\">Some placeholder content in a paragraph below the heading and date.</div>\r\n");
      out.write("      </a>\r\n");
      out.write("      <a href=\"#\" class=\"list-group-item list-group-item-action py-3 lh-sm\">\r\n");
      out.write("        <div class=\"d-flex w-100 align-items-center justify-content-between\">\r\n");
      out.write("          <strong class=\"mb-1\">List group item heading</strong>\r\n");
      out.write("          <small class=\"text-body-secondary\">Tues</small>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-10 mb-1 small\">Some placeholder content in a paragraph below the heading and date.</div>\r\n");
      out.write("      </a>\r\n");
      out.write("      <a href=\"#\" class=\"list-group-item list-group-item-action py-3 lh-sm\">\r\n");
      out.write("        <div class=\"d-flex w-100 align-items-center justify-content-between\">\r\n");
      out.write("          <strong class=\"mb-1\">List group item heading</strong>\r\n");
      out.write("          <small class=\"text-body-secondary\">Mon</small>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-10 mb-1 small\">Some placeholder content in a paragraph below the heading and date.</div>\r\n");
      out.write("      </a>\r\n");
      out.write("      <a href=\"#\" class=\"list-group-item list-group-item-action py-3 lh-sm\" aria-current=\"true\">\r\n");
      out.write("        <div class=\"d-flex w-100 align-items-center justify-content-between\">\r\n");
      out.write("          <strong class=\"mb-1\">List group item heading</strong>\r\n");
      out.write("          <small class=\"text-body-secondary\">Wed</small>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-10 mb-1 small\">Some placeholder content in a paragraph below the heading and date.</div>\r\n");
      out.write("      </a>\r\n");
      out.write("      <a href=\"#\" class=\"list-group-item list-group-item-action py-3 lh-sm\">\r\n");
      out.write("        <div class=\"d-flex w-100 align-items-center justify-content-between\">\r\n");
      out.write("          <strong class=\"mb-1\">List group item heading</strong>\r\n");
      out.write("          <small class=\"text-body-secondary\">Tues</small>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-10 mb-1 small\">Some placeholder content in a paragraph below the heading and date.</div>\r\n");
      out.write("      </a>\r\n");
      out.write("      <a href=\"#\" class=\"list-group-item list-group-item-action py-3 lh-sm\">\r\n");
      out.write("        <div class=\"d-flex w-100 align-items-center justify-content-between\">\r\n");
      out.write("          <strong class=\"mb-1\">List group item heading</strong>\r\n");
      out.write("          <small class=\"text-body-secondary\">Mon</small>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-10 mb-1 small\">Some placeholder content in a paragraph below the heading and date.</div>\r\n");
      out.write("      </a>\r\n");
      out.write("      <a href=\"#\" class=\"list-group-item list-group-item-action py-3 lh-sm\" aria-current=\"true\">\r\n");
      out.write("        <div class=\"d-flex w-100 align-items-center justify-content-between\">\r\n");
      out.write("          <strong class=\"mb-1\">List group item heading</strong>\r\n");
      out.write("          <small class=\"text-body-secondary\">Wed</small>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-10 mb-1 small\">Some placeholder content in a paragraph below the heading and date.</div>\r\n");
      out.write("      </a>\r\n");
      out.write("      <a href=\"#\" class=\"list-group-item list-group-item-action py-3 lh-sm\">\r\n");
      out.write("        <div class=\"d-flex w-100 align-items-center justify-content-between\">\r\n");
      out.write("          <strong class=\"mb-1\">List group item heading</strong>\r\n");
      out.write("          <small class=\"text-body-secondary\">Tues</small>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-10 mb-1 small\">Some placeholder content in a paragraph below the heading and date.</div>\r\n");
      out.write("      </a>\r\n");
      out.write("      <a href=\"#\" class=\"list-group-item list-group-item-action py-3 lh-sm\">\r\n");
      out.write("        <div class=\"d-flex w-100 align-items-center justify-content-between\">\r\n");
      out.write("          <strong class=\"mb-1\">List group item heading</strong>\r\n");
      out.write("          <small class=\"text-body-secondary\">Mon</small>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-10 mb-1 small\">Some placeholder content in a paragraph below the heading and date.</div>\r\n");
      out.write("      </a>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"b-example-divider b-example-vr\"></div>\r\n");
      out.write("</main>\r\n");
      out.write("<script src=\"/docs/5.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"sidebars.js\"></script></body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
